### PR TITLE
osx_arm64 build

### PR DESCRIPTION
**Pull request by mmcauliffe**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by kylebgorman — APPROVED** [review]
LGTM

**Comment by mmcauliffe** [comment]
Cool, it should be ready for you to merge whenever!

**Comment by mmcauliffe** [comment]
Odd, it looks like the azure build failed for the merged version due to not finding openfst for arm64, even though it could on the PR.  Can you retrigger the build at some point?

**Comment by kylebgorman** [comment]
What’s the magic Incantation do you remember?

K

**Comment by mmcauliffe** [comment]
I just did a meaningless commit to retrigger it before, I remember there was an ability to restart azure pipelines for conda forge feedstocks from their failed actions, but there wasn't an option showing up for me, but that could be because of permissions

**Pull request merged**
